.TH LMORSE 6 "2012-03-27" "Danyl S. Nysom" "Danyl S. Nysom's Toolkit of Joy"
.SH NAME
lmorse - Danyl S. Nysom's LED Morse Generator of Joy
.SH SYNOPSIS
.BI "led_morse [" "OPTION" "]... " "MESSAGE"
.SH DESCRIPTION
Outputs, in morse code, the MESSAGE by flashing the keyboard LEDs
.SH OPTIONS
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
.BR "-p" ", " "--proper"
Do 'proper' morse output, with the start- and end-
of-transmission characters output
.TP
.BR "-t" ", " "--translations-file="\fIFILE
Read translations from FILE instead of the default translations file.
Multiple translations files can be used concurrently, by specifying each
with its own
.B -t
flag
.TP
.BR "-?" ", " "--help"
Output information about command line options
.TP
.B --usage
Give a short usage message
.TP
.BR "-V" ", " "--version"
Print program version
.TP
.B --
A -- signals the end of options and disables further option processing.
Any arguments after the -- are treated as parts of the message.
.SH EXIT STATUS
.TP
0
if OK,
.TP
1
on any error.
.SH FILES
Uses the device
.I /dev/myleds
to control the keyboard LEDs.
.SH CONFORMING TO
C89
.SH NOTES
Uppercase and lowercase characters are treated equally in the message,
as well as in custom translations files.
.SH AUTHOR
Written by Danyl S. Nysom (aka Dylan Symons 100184844)
.SH SEE ALSO
myleds(4)
